// src/routes/_navbar.svelte
<div>
	<nav class="navbar has-shadow is-fixed-top" role="navigation" aria-label="main navigation">
		<div class="container">
			<div class="navbar-brand">
				<a
					role="button"
					class="navbar-burger"
					aria-label="menu"
					aria-expanded="false"
					data-target="navlist"
					onclick="document.querySelector('#navlist').classList.toggle('is-active');"
				>
					<span aria-hidden="true" />
					<span aria-hidden="true" />
					<span aria-hidden="true" />
				</a>
			</div>

			<div id="navlist" class="navbar-menu" style="margin-right: 50px">
				<div class="navbar-end">
					<a class="navbar-item is-tab" href="/">Home</a>
					<a class="navbar-item is-tab" href="/case-studies">Case studies</a>
					<a class="navbar-item is-tab" href="/about">About</a>
				</div>
			</div>
		</div>
	</nav>
</div>

// src/views/Navbar.vue
<template>
  <nav
    class="navbar has-shadow is-fixed-top"
    role="navigation"
    aria-label="main navigation"
  >
    <div class="container">
      <div class="navbar-brand">
        <a
          role="button"
          class="navbar-burger"
          aria-label="menu"
          aria-expanded="false"
          data-target="navlist"
          onclick="document.querySelector('#navlist').classList.toggle('is-active');"
        >
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navlist" class="navbar-menu" style="margin-right: 50px">
        <div class="navbar-end">
          <a class="navbar-item is-tab" href="/">Home</a>
          <a class="navbar-item is-tab" href="/case-studies">Case studies</a>
          <a class="navbar-item is-tab" href="/about">About</a>
        </div>
      </div>
    </div>
  </nav>
</template>
