// src/routes/about/_consulting.svelte
<div id="consulting">
	<h2>Consulting</h2>
	<div>
		I am occasionally available for statistical consulting on probabilistic modeling, causal
		inference, and research software development. In particular, I offer consulting on
		<ul>
			<li>
				statistical/causal data analysis, e.g., of biomedical, financial, or astrophysical data sets
			</li>
			<li>development of web dashboards for visualization</li>
			<li>implementation of bespoke probabilistic models using PPLs (*)</li>
			<li>Bayesian workflow, model validation, model selection, etc.</li>
			<li>
				implementation of computational pipelines (e.g., of analysis workflows for reproducible
				research)
			</li>
		</ul>
		(*) via, e.g, Stan, NumPyro or TensorFlow Probability (in Python, Julia, C++ or R)<br />
		To find a sketch of topics that I have expertise with, please have a look at my
		<a href="/case-studies">case studies</a>.
	</div>
</div>

// src/components/Consulting.vue
<template>
  <div id="consulting">
    <h2>Consulting</h2>
    <div>
      I am occasionally available for statistical consulting on probabilistic
      modeling, causal inference, and research software development. In
      particular, I offer consulting on
      <ul>
        <li>
          statistical/causal data analysis, e.g., of biomedical, financial, or
          astrophysical data sets
        </li>
        <li>development of web dashboards for visualization</li>
        <li>implementation of bespoke probabilistic models using PPLs (*)</li>
        <li>Bayesian workflow, model validation, model selection, etc.</li>
        <li>
          implementation of computational pipelines (e.g., of analysis workflows
          for reproducible research)
        </li>
      </ul>
      (*) via, e.g, Stan, NumPyro or TensorFlow Probability (in Python, Julia, C++ or R) <br />
      To find a sketch of topics that I have expertise with, please have a look
      at my <a href="/case-studies">case studies</a>.
    </div>
  </div>
</template>
