// src/views/Consulting.vue
<template>
  <section class="section" style="margin-top: 1%">
    <div class="container">
      <div class="columns">
        <div class="column is-offset-1 is-3">
          <h1>Consulting</h1>
        </div>
        <div class="column is-6" style="margin-top: 2%;">
          <consulting />
          <bottom />
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import consulting from "../components/Consulting.vue";
import bottom from "../components/Bottom.vue";

export default {
  components: {
    consulting,
    bottom
  },
  watch: {
    title: {
      immediate: true,
      handler() {
        document.title = "Consulting";
      }
    }
  }
};
</script>

// src/routes/consulting/+page.svelte
<script>
    import Navv from '../_navbar.svelte';
    import Bottom from '../_bottom.svelte';
    import Consulting from './_consulting.svelte';
</script>

<svelte:head>
    <title>consulting</title>
</svelte:head>

<div>
    <Navv/>
    <div>
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-4 is-6">
                        <Consulting />
                        <Bottom />
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
